In [3]:
import numpy as np

<div style="float:center;width:100%;text-align:center;"><strong style="height:100px;color:darkred;font-size:40px;">The Algebra of Vector and Matrix Operations</strong>
</div>

# 1. Algebra

## 1.1 Preliminary Remarks: Addition and Scalar Multiplication

* We already have the algebra of Addition and Scalar Multiplication
* Vectors can be Considered a Special Case of Matrices

#### **Reminder:**

<div style="background-color:#F2F5A9;align:left;width:100%;">
<strong>Theorem:</strong> Given any matrices $A, B, C$ in $\mathbb{F}^{m \times n}$ and any scalars $\alpha, \beta$ in $\mathbb{F}$
<br><br>
<div style="background-color:#F2F5A9;align:left;width:100%;height:2.5cm;">
<div style="float:left;width:48%;background-color:#F2F5A9;padding-right:2mm;padding-left:1mm;">
$$\begin{align}
& A + B = B + A                                                        & \text{(commutativity)} \\
& (A + B) + C = A + (B + C) \quad                                      & \text{(associativity)} \\
& \exists 0 \in \mathbb{F}^{m \times n} \ni A + 0 = A                  & \text{(identity element for matrix addition)} \\
& \exists \tilde{A}  \in \mathbb{F}^{m \times n} \ni A + \tilde{A} = 0 & \text{(existence of the additive inverse)}\\
\end{align}
$$
</div>
<div style="float:left;width:48%;background-color:#F2F5A9;border-left: 2px solid black;">
$$\begin{align}
&    \alpha \left( A + B \right) = (\alpha A) + (\alpha B) \;\;              &  \text{(distributivity of scalar mult over Matrix addition)}\\
&    \left( \alpha + \beta \right) A = (\alpha A) + (\beta A) \;\;          &  \text{(distributivity of scalar mult over scalar addition)}\\
&    \alpha \left( \beta A \right) = \left( \alpha \beta \right) A \;\;     & \text{(compatibility of addition and scalar mult)}\\
&    1 A = A                                                                & \text{(identity element for scalar mult)} \\
\end{align}
$$
</div></div>    
<\div>

<div style="background-color:#F2F5A9;">
<strong>Theorem:</strong>

* The **zero element is unique**. It is $\color{red}{0 = \begin{pmatrix} 0 & 0 & \dots & 0 \\
                                                                         0 & 0 & \dots & 0 \\
                                                                         \dots & \dots & \dots & \dots
\end{pmatrix}}$<br><br>
    * The scalar product $\color{red}{ \quad 0\ A = 0 } \qquad$  (note the 0 on the left is a scalar, the 0 on the right is the zero matrix)<br><br>
* The **additive inverse is unique**.
    * The additive inverse of a matrix $A$ is $\color{red}{ \quad \tilde{A} = -1 A}$
</div>

## 1.2 The Product $\mathbf{ A B }$

#### **The Product is not Commutative in General:** $\mathbf{ A B \ne B A}$

<div>

> $A = \begin{pmatrix} 1 & 1 & 2 \\ -1 & 0 & 1 \end{pmatrix}, \quad B = \left(\begin{array}{rrr} 1 & 1 & 1 \\ -1 & 0 & 0 \\ 1 & -1 & 1 \end{array}\right)
\quad \Rightarrow \quad A B = \left(\begin{array}{rrr} 2 & -1 & 3 \\ 0 & -2 & 0 \end{array}\right), \quad
$ but $B A$ does not exist due to a size mismatch: $B_{\color{red}{3 \times \mathbf 3}} A_{\color{red}{\mathbf 2 \times 3}}$
</div>

> $B A$ does not exist: for $A B$ and $B A$ to exist, they are subject to a **size constraint:** $\quad A_{\mathbf{m \times n}}, \; B_{\mathbf{n \times m}}$
> * if $m \ne n$, $A B$ has size $m \times m$, but $B A$ has size $n \times n$.

<div>

> $A = \left(\begin{array}{rr} 1 & 1 \\ 2 & -1 \end{array}\right), \quad
   B = \left(\begin{array}{rr} 1 & 3 \\ -2 & 4 \end{array}\right)
\quad \Rightarrow \quad A B = \left(\begin{array}{rr} -1 & 7 \\ 4 & 2 \end{array}\right), \quad
B A = \left(\begin{array}{rr} 7 & -2 \\ 6 & -6 \end{array}\right)
$ $\quad$ so $\mathbf{A B \ne B A}$
</div>

<div>

> $A = \left(\begin{array}{rr} 2 & 3 \\ 2 & 3 \end{array}\right), \quad
   B = \left(\begin{array}{rr} 1 & 3 \\ 2 & 2 \end{array}\right)
\quad \Rightarrow \quad A B = B A = \left(\begin{array}{rrr} 8 & 12 \\ 8 & 12 \end{array}\right)
$
</div>

#### **The Power of a Square Matrix**

If $A$ is **square,** i.e., if it has size $n \times n$, we denote $A^k = A A \dots A$, the product of $k$ matrices $A$.

> $A = \left(\begin{array}{rr} -1 & 2 \\ -3 & 4 \end{array}\right) \; \Rightarrow A^3 = A\ A\ A = \left(\begin{array}{rr} -13 & 14 \\ -21 & 22 \end{array}\right)$

#### **Some Special Matrices**

##### **The Zero Matrix**

$0 A = 0$, $A 0 = 0$

> $ 0 A = \begin{pmatrix} 0 & 0 \\ 0 & 0 \\ 0 & 0 \end{pmatrix} \left(\begin{array}{rrr} -1 & 2 & 3 & 1 \\ -3 & 4 & 2 & 1 \end{array}\right) =
\left(\begin{array}{rr} 0 & 0 &  0 & 0 \\ 0 & 0 &  0 & 0  \\ 0 & 0  &  0 & 0  \end{array}\right)\, \qquad\qquad
A 0 = \left(\begin{array}{rrr} -1 & 2 & 3 & 1 \\ -3 & 4 & 2 & 1 \end{array}\right) \begin{pmatrix} 0& 0 \\ 0 & 0 \\ 0 & 0 \\ 0 & 0 \end{pmatrix} = \begin{pmatrix} 0 & 0 \\ 0 & 0 \end{pmatrix}$

##### **The Identity Matrix**

**Definition:** An **identity matrix** $I$ of size $n \times n$ has entries 1 on the main diagonal, and zero everywhere else.
$$
I = \begin{pmatrix} 1 &    0 & \dots & \dots & 0 \\
                    0 &    1 & \dots & \dots & 0 \\
                    \dots &\dots & \ddots & \dots & \dots\\
                    0 &\dots & \dots & \ddots & 0 \\
                    0 &\dots  & \dots & \dots & 1 \end{pmatrix}
$$

> $I A = A$ each row of $I$ copies the corresponding row fo $A$ into the product<br>
> $A I = A$ each column of $I$ copies the corresponding column of $A$ into the product

#### **Remarks:**

<div><div style="float:left;width:60%;"> 

* $\alpha A = A ( \alpha I )$<br>
> $3 \begin{pmatrix} 1&2&3\\1&2&3\end{pmatrix} = \begin{pmatrix}1&2&3\\1&2&3\end{pmatrix} \begin{pmatrix}3&0&0\\0&3&0 \\ 0&0&3\end{pmatrix} $
</div></div>

<div style="float:left;width:60%;"> 

* we can select rows / columns from $A$ by multiplying with<br>$\quad$ the corresponding rows/columns of $I$
>  * extract rows 1 and 3 from a matrix:<br>
>  $\left(\begin{array}{ccc} 1 & 0 & 0\\\hline  0 & 0 & 1 \end{array}\right)
   \begin{pmatrix} 1 & 1 & 1 & 1 \\ 2 & 2 &2 & 2 \\ 3 & 3 & 3 & 3\end{pmatrix} = \left(\begin{array} {ccc}1&1&1&1 \\ \hline 3 &3&3&3 \end{array}\right) $
</div><div style="float:left;width:35%;padding-top:1.6cm;padding-left:1cm;";><img src="Figs/mat_alg1.svg"></div>

<div style="float:left;width:60%;padding-left:0.8cm;"> 

>   *  extract columns 1 and 3 from a matrix:<br>
>$\begin{pmatrix} 1&2&3 \\ 1&2 &3 \end{pmatrix} \left(\begin{array}{c|c} 1 & 0 \\ 0 & 0 \\ 0 & 1 \end{array}\right) = \left(\begin{array}{c|c} 1&3 \\ 1 &3 \end{array}\right) $
</div>
<div style="float:left;width:30%;padding-top:0.5cm;padding-left:1cm;";><img src="Figs/mat_alg2.svg"></div>

##### **Permutation Matrices**

**Permutation Matrices** are identity matrices with some rows (columns) interchanged<br>
$\quad$ They can be used to interchange rows (columns) of a matrix

<div style="float:left;width:60%;"> 

> * exchange rows 1 and 3 of a matrix:<br>
> $\left(\begin{array}{ccc} 0 & 0 & 1\\ \hline 0&1&0 \\ \hline 1 & 0 & 0 \end{array} \right)
   \begin{pmatrix} 1 & 1 & 1 & 1 \\ 2 & 2 &2 & 2 \\ 3 & 3 & 3 & 3\end{pmatrix} = \left(\begin{array}{cccc} 3 &3&3&3 \\ \hline 2&2&2&2 \\ \hline 1&1&1&1 \end{array} \right)$
</div><div style="float:left;width:30%;padding-top:0cm;padding-left:1cm;";><img src="Figs/mat_alg3.svg"></div>

<div style="float:left;width:60%;"> 

> *  exchange columns 1 and 3 of a matrix:<br>
> $\begin{pmatrix} 1&2&3 \\ 1&2 &3 \end{pmatrix} \left(\begin{array}{c|c|c} 0 & 0 & 1\\0&1&0 \\ 1 & 0 & 0 \end{array} \right) = \left(\begin{array}{c|c|c} 3&2&1 \\ 3 &2&1 \end{array} \right) $
</div><div style="float:left;width:30%;padding-top:1cm;padding-left:0.3cm;";><img src="Figs/mat_alg4.svg"></div>

## 1.3 Properties of Matrix Multiplication

<div style="float:left;background-color:#F2F5A9;padding-right:1cm;height:4.7cm;width:42%;">

**Theorem:** Assuming $A, B$ and $C$ are matrices of **consistent sizes,**<br>$\quad$ such that the operations below are defined.<br>
    $\quad$ Let $\alpha$ be any scalar, then
* $( A B ) C = A ( B C )$
* $A ( B + C) = A B + A C$ $\;\;$ and $\;\;$  $( B + C ) A = B A + C A$
* $\alpha (A B) = (\alpha A) B = A (\alpha B)$
</div>
<div style="float:left;background-color:#F2F5A9;height:4.7cm;width:48%;padding-left:1cm;padding-right:0.5cm;border-left:2px solid black;">

**Theorem:** Assuming $A$ and $B$ are matrices of **consistent sizes,**<br>$\quad$  such that the operations below are defined
* $(A^t)^t = A$
* $(A + B)^t = (A^t) + (B^t) \quad  \text{drop the parentheses on the right hand sides:} A^t + B^t$
* $(\alpha A)^t = \alpha A^t$
* $(A B)^t = B^t A^t$
</div>

<div style="float:left;padding-left:1cm;padding-right:1cm;">

Compare the layouts for $A B$ and $B^t A^t$

Since we lay out the matrices in the left column of the display<br>
    $\qquad$ **as rows**,<br>
and the matrices in the top rows of the display<br>
    $\qquad$ **as columns**,<br>
<strong style="color:darkred;text-size:20px;">the products are $A B$ and $B^t A^t$ respectively</strong>
</div>
<div style="float:left;padding-left:2cm;padding-right:1cm;">

The product $A B$

$ $   | $\color{darkred}{b_1}  $  | $ \color{darkred}{b_2} $ | $\dots $ |
------|-----------------       |------------------    | --- |
$\color{darkred}{a_1}$ | $a_1 \cdot b_1$        | $a_1 \cdot b_2$      | $\dots $ |
$\color{darkred}{a_2}$ | $a_2 \cdot b_1$        | $a_2 \cdot b_2$      | $\dots $ |
$\dots $ |  $\dots $ |  $\dots $ |  $\dots $ |
</div>
<div style="float:left;padding-left:3cm;padding-right:1cm;">


The product $B^t A^t$

$ $   | $\color{darkred}{a_1}  $  | $ \color{darkred}{a_2} $ | $\dots $ |
------|-----------------       |------------------    | --- |
$\color{darkred}{b_1}$ | $a_1 \cdot b_1$        | $a_2 \cdot b_1$      | $\dots $ |
$\color{darkred}{b_2}$ | $a_1 \cdot b_2$        | $a_2 \cdot b_2$      | $\dots $ |
$\dots $ |  $\dots $ |  $\dots $ |  $\dots $ |
</div>

#### **Caveats: Beware of Scalar Algebra Patterns**

**Can't interchange Matrices in a Product:** $A B \ne B A$

##### **No Division**

* $\mathbf{ A B = 0}$ **does not imply** $\mathbf{ A = 0}$ **or** $\mathbf{ B = 0}$

> $\left(\begin{array}{rr} 1 & 2 \\ 2 & 4\end{array}\right)\left(\begin{array}{rr} -2 & 4 \\ 1 & -2\end{array}\right) \;=\; \begin{pmatrix} 0 & 0 \\ 0 & 0 \end{pmatrix},$
$\qquad\qquad$
$\begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix}^2 = \begin{pmatrix} 0 & 0 \\ 0 & 0 \end{pmatrix}$

* $ \mathbf{A B = A C} $ **does not imply** $\mathbf{B = C}$ $\quad$ No cancelation! The best we can do is $\quad \mathbf{ A B = A C \Leftrightarrow A ( B - C ) = 0}$

##### **Multiplication Patterns do not Hold**

<div style="float:left;padding-right:3cm;">
$\begin{align}(A + B)(A + B) &= A (A+B) + B (A+B)\\ &= A^2 + A B + B A + B^2 \end{align}$
</div>
<div style="float:left;padding-left:3cm;border-left:2px solid black;">
$\begin{align}(A + B)(A - B) &= A (A-B) + B (A-B)\\ &= A^2 - A B + B A - B^2 \end{align}$
</div>

## 1.4 The Dot Product Compared to Matrix Multiplication

<div style="width:100%;">
<div style="float:left;background-color:#F2F5A9;padding-right:1.cm;height:5cm;width:35%;">

**Theorem:** Assuming $u, v$ and $w$ are vectors of **consistent sizes,**<br>$\quad$ such that the operations below are defined.<br>
    $\quad$ Let $\alpha$ be any scalar, then
* $u \cdot v = v \cdot u$
* $u \cdot ( v + w) = u \cdot v + u \cdot w$
* $\alpha (u \cdot v) = (\alpha u) \cdot v = u \cdot (\alpha v)$
</div>
<div style="float:left;padding-left:2cm;height:5cm;width:58%;">


* $ ( A B )^t = B^t A^t$ simplifies: let $A = u^t, B = v\; \Rightarrow\; (u^t v)^t = v^t u\; \Rightarrow\; u \cdot v = v \cdot u$
* Thus $\quad (u-v) \cdot (u+v) = u\cdot u - v \cdot v$
* No division: $u \cdot v = u \cdot w\; \Leftrightarrow\; u \cdot \left( v - w \right) = 0$.<br>
    but $u \cdot v = 0$ does not let us conclude $u = 0$ or $v = 0,$ e.g.,<br><br>
    $\begin{pmatrix} 1 \\ 2 \end{pmatrix} \cdot \left( \begin{array}{r} -2 \\ 1 \end{array} \right) = 0$ 
</div>
</div>

# 2. Examples

## 2.1 Products of More than 2 Matrices

**Products of More than 2 Matrices Can be Chained**

> Consider $A = \begin{pmatrix} 1 & 2 & 2\\ 2 & 0 & 3 \end{pmatrix}, \quad
B = \begin{pmatrix} 3 & 1 \\ 0 & 1 \\ 2 & 2 \end{pmatrix}, \quad
C = \left(\begin{array}{rr} 2 & 2 & 1 & 1\\ -2 & -1 & 0 & -1\end{array}\right)$

<div style="float:left;padding-right:2cm;">

> <!--
$\begin{array}{rrr|rr|rrrr}
  &   &   &    3 & 1   &   &   &   &   & \\
  &   &   &    0 & 1   & 2 & 2 & 1 & 1 & \\
  &   &   &    2 & 2   &-2 &-1 & 0 & 1 & \\ \hline
% -----------------------------------
1 & 2 & 2 &    7 & 7   & 0 & 7 & 7 & 0 & \\
2 & 0 & 3 &   12 & 8   & 8 &16 &12 & 4 & \\
\end{array}$ -->
Compute: $(A B) C$
>
> <img src="Figs/mat_alg5.svg">
</div>
<div style="float:left;border-left:2px solid black; padding-left:3cm;">

<!--
$\begin{array}{rrr|rrrrr}
  &   &        &  2 & 2 & 1 & 1 & \\
  &   &        & -2 &-1 & 0 & 1 & \\ \hline
% -----------------------------------
  & 3 & 1      &  4 & 5 & 3 & 2 & \\
  & 0 & 1      & -2 &-1 & 0 &-1 & \\
  & 2 & 2      &  0 & 2 & 2 & 0 & \\ \hline
% --------------------------------------
1 & 2 & 2      &  0 & 7 & 7 & 0 & \\
2 & 0 & 3      &  8 &16 &12 & 4 & \\
\end{array}$ -->
Compute: $A (B C)$

<img src="Figs/mat_alg6.svg">

**Remark:** Different groupings (how to place parentheses)<br> $\quad$ can require different numbers of multiplications<br>
$\quad$ <strong style="text-size:20px;color:darkred;">Count them for this example!</strong>

In [6]:
A=np.array( [[1, 2, 2],
             [2, 0, 3]])

B = np.array([[3, 1], [0, 1], [2, 2]])
C = np.array([[2, 2, 1, 1], [-2, -1, 0, -1]])

A @ (B @ C)

array([[ 0,  7,  7,  0],
       [ 8, 16, 12,  4]])

## 2.2 Substitution is Matrix Multiplication

> Consider $\qquad\quad$ $(\xi) \Leftrightarrow \left\{ \begin{align} 3 x_1 + 2 x_2 & = 8 \\ 5 x_1 - 5 x_2 &= 5 \end{align}\right. \quad$
i.e., $\quad (\xi) \Leftrightarrow A x = b,\quad$  where 
> $\quad x = \begin{pmatrix} x_1 \\ x_2 \end{pmatrix},$
  $\quad A = \left( \begin{array}{rr} 3 & 2 \\ 5 & -5  \end{array}\right),
   \quad b = \begin{pmatrix} 8 \\ 5 \end{pmatrix},$<br>
> 

> and substitute
$\quad\;\;\; (\zeta) \Leftrightarrow \left\{ \begin{align} x_1 &= 2 \tilde{x}_1 - \tilde{x}_2 \\ x_2 &= 3 \tilde{x}_1 + \tilde{x}_2 \end{align}\right.$
$\quad$ i.e.,
$\quad (\zeta) \Leftrightarrow x = B\ \tilde{x}, \;\;$ where
$\quad \tilde{x} = \begin{pmatrix} \tilde{x}_1 \\ \tilde{x}_2 \end{pmatrix},$
$\quad B = \left(\begin{array}{rr} 2 & -1 \\ 3 & 1 \end{array}\right)$

> Substitution of $(\zeta)$ into $(\xi)$ directly yields $\left\{ \begin{align}12 \tilde{x}_1 &- \tilde{x}_2 &= 8 \\ -5 \tilde{x_1} &-10 \tilde{x}_2 &= 5 \end{align}\right.$

> We can obtain the coefficients directly: $A x = b$ and $x = B \tilde{x} \Rightarrow A B \tilde{x} = b$, so the coefficients are given by the product $A B$.

In [7]:
A=np.array([[3, 2], [5,-5]])
B=np.array([[2, -1], [3, 1]])

display("A =",    A)
display("B =",    B)
display("A B = ", A @ B )

'A ='

array([[ 3,  2],
       [ 5, -5]])

'B ='

array([[ 2, -1],
       [ 3,  1]])

'A B = '

array([[ 12,  -1],
       [ -5, -10]])

# 3. Take Away

* We have obtained the algebra of **matrix addition, scalar multiplication and matrix multiplication**
* The equations look similar to scalar equations and can be manipulated in the same way, except for
    * there is **no division by a matrix** (although we will see special cases later)
    * the matrix product **does not commute**, so scalar equation patterns learned for speed<br>
    do not apply in general.

* We saw some special matrices and their action in a matrix product:
    * the **zero matrix**
    * the **identity matrix** and submatrices of the identity matrix
    * **permutation matrices**

* Stacking matrices in a **layout to perform matrix multiplication**<br>
combined with **partitioning** will prove very useful