In [1]:
using LinearAlgebra, RowEchelon, LaTeXStrings, Plots
using SymPy, Latexify
#using LAcode
#include("LAcodes.jl")
;

<div style="float:center;width:100%;text-align: center;"><strong style="height:100px;color:darkred;font-size:40px;">Linear Transformations and Analytic Geometry</strong></div>

# 1. Formulae from Trigonometry

## 1.1 Euler's Formula

<div style="background-color:#F2F5A9;">
    <strong>Theorem:</strong><br>
$\quad$ Given $\theta \in \mathbb{R}$ we have $e^{i \theta} = cos \theta + i \ sin \theta$
<div>

The formula is readily generalized to complex numbers $z = x + i \ y$. Properties we will use are
$$\begin{align}
    e^{x + i y} =&\ e^x e^{ i y} = e^x \left( cos y + i\ sin y \right) & \qquad & \text{for any } x,y \in \mathbb{R}\\
    e^{z+w} =&\ e^z + e^w & \qquad & \text{for any } z,w \in \mathbb{C}
\end{align}$$

**Remarks:**
* If we set $r = e^x, \ \theta = y,$ we see that $e^{x+i\ y} =r e^{i\ \theta}$ can be interpreted as a representation of a point in polar coordinates.

## 1.2 Formulae based on Euler's Formula and Complex Multiplication

Cosine and sine values for the angles $0^\circ, 30^\circ, 45^\circ, 60^\circ$ and $90^\circ$ in increasing order<br> are easy to remember.

<div style="float:left;padding-right:1cm;border-right:2px solid black;">
    Here is a <strong>mnemnonic:</strong>

| angle $\theta$ | $0^\circ$ | $30^\circ$ | $45^\circ$ | $60^\circ$ | $90^\circ$ |
| :---- | --- | --- | ---- | ---- | ---- |
| sin$\ \theta$   |  $\tfrac{\sqrt{\color{red}0}}{2}$ |$\tfrac{\sqrt{\color{red}1}}{2}$ | $\tfrac{\sqrt{\color{red}3}}{2}$ | $\tfrac{\sqrt{\color{red}3}}{2}$| $\tfrac{\sqrt{\color{red}4}}{2}$|
| cos$\ \theta$   |  $\tfrac{\sqrt{\color{red}4}}{2}$ |$\tfrac{\sqrt{\color{red}3}}{2}$ | $\tfrac{\sqrt{\color{red}2}}{2}$ | $\tfrac{\sqrt{\color{red}1}}{2}$| $\tfrac{\sqrt{\color{red}0}}{2}$|
</div>
<div style="float:left;padding-left:1cm;">
Addition of angles is easily handled by the formulae for the exponentials and complex multiplication:

$$\begin{align}
\color{red}{cos\ ( \theta + \phi )} + i \color{blue}{\ sin ( \theta + \phi )}
    =&\ e^{i\ (\theta + \phi )} \\
    =&\ e^{i \ \theta} e^{i \ \phi} \\
    =&\ \left( cos \ \theta + i \ sin\ \theta \right) \left( cos \ \phi + i \ sin\ \phi \right) \\
    =&\ \color{red}{ cos \ \theta\ cos \ \phi - sin\ \theta\ sin\ \phi}
      +  i \ \color{blue}{\left( cos \ \theta\ sin \ \phi + sin\ \theta\ cos\ \phi \right) } \\
\end{align}$$
</div>

**Special Cases:**<br>
<div style="float:left;padding-right:1cm;">
$$\begin{align}
e^{\frac{\pi}{2}i} =&\ \;\;\; i \;\;( 90^\circ ) \\
e^{\pi i} =&\ \; -1 \;\;( 180^\circ ) \\
e^{-\frac{\pi}{2}i} =&\ - i \;\;( 90^\circ ) \\
\end{align}$$
</div>
<div style="float:left;padding-left:1cm;padding-right:1cm;border-left:2px solid black;border-right:2px solid black;">

Since $120^\circ = 90^\circ + 30^\circ$, we have

$$\begin{align}
\color{red}{cos \ 120^\circ} + i \color{blue}{\ sin\ 120^\circ} =&\  e^{\frac{\pi}{2}i}\; e^{\frac{\pi}{3}i}\\
                                     =&\ i\ e^{\frac{\pi}{3} i} \\
                                     =&\ \color{red}{-\frac{1}{2}} +i \color{blue}{\ \frac{\sqrt{3}}{2}}
\end{align}$$
</div>
<div style="float:left;padding-left:1cm;">
$$\begin{align}
\color{red}{cos\ ( \theta + \pi )} + i \color{blue}{\ sin ( \theta + \pi )}
    =&\ e^{i\ (\theta + \pi )} \\
    =&\ e^{i \ \theta} e^{i \ \pi} \\
    =&\ \left( cos \ \theta + i \ sin\ \theta \right) \left( -i \right) \\
    =&\ \color{red}{ sin \ \theta } - i \ \color{blue}{ cos\ \theta } \\
\end{align}$$

# 2. Linear Transforms Using Analytic Geometry

Coordinates of points can often be determined easily using **polar coordinates!**

### 2.1 Reflection With Respect To a Line

Consider the reflection of a point $A$ with respect to a a line $y = x\; \tan \phi$, as shown in the following diagram:

<div style="float:left;">
<img src="./Figs/LinTxSymLine.svg"  width="200">
</div>
<div style="float:left;padding-left:3cm;">

<br>

Observe that the triangles OCA and OCB are congruent:
* The angles $\angle OCB = \angle OCA = 90^\circ$
* The side $OC$ is in common
* The side $AC = CB$ by construction

Given a point $A$ at $(r \cos \theta, r \sin \theta)$, we see that<br>$\quad$ the reflected point $B$ has coordinates
$\left(r \cos ( 2 \phi - \theta ), r \sin ( 2 \phi- \theta) \right)$

</div>

This problem is simple enough that we can write down the solution directly:
* start with the point $A$ with polar coordinates $\left[ r, \theta \right]$
* draw the orthogonal reflection $B$ through a line $(L)$ that makes an angle $\phi$ with respect to the x axis
* show the triangles $OCA$ and $OCB$ are congruent and derive the angles
* the point $B$ is at a distance $r$ from the origin and an angle $\phi+(\phi - \theta) = 2\phi - \theta$ with respect to the x axis

Therefore, expanding using trigonometric identities, we have

$$
\begin{pmatrix} x' \\ y' \end{pmatrix} = \begin{pmatrix} r \cos(2 \phi - \theta) \\ r \sin( 2 \phi -\theta)\end{pmatrix}
= \begin{pmatrix} r \cos(2\phi) \cos(\theta)+ r \sin(2\phi) \sin(\theta) \\ r \sin(2\phi) \cos(\theta)- r \cos(2\phi)\sin(\theta) \end{pmatrix}
= \begin{pmatrix} \cos( 2 \phi) & \sin( 2 \phi) \\ \sin(2\phi) & - \cos(2\phi) \end{pmatrix}
  \begin{pmatrix} r \cos(\theta) \\ r \sin(\theta) \end{pmatrix}
= \begin{pmatrix} \cos( 2 \phi) & \sin( 2 \phi) \\ \sin(2\phi) & - \cos(2\phi) \end{pmatrix}
  \begin{pmatrix} x \\ y \end{pmatrix}
$$

**Remark:**<br>
$\quad$ We found that coordinates of $B$ are obtained from the coordinates of $A$ by multiplication with a matrix<br>
$\quad$ Since this matrix does not depend on the coordinates of $A$, the orthogonal reflection through a line is a **linear transformation.** 

## 2.2 Orthogonal Projection Onto a Line

The problem is again simple enough so we can write the solution directly: we observe

$$OC = OA + \frac{1}{2} AB = OA + \frac{1}{2} \left( OB - OA \right)$$

Therefore, using the reflection result above

$$
\begin{pmatrix}x' \\ y' \end{pmatrix} = \begin{pmatrix}x \\ y \end{pmatrix}
+ \frac{1}{2} \left( \;
 \begin{pmatrix} \cos (2\phi) & \sin (2\phi) \\ \sin (2\phi) & -\cos (2\phi) \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix}
- \begin{pmatrix} x \\ y \end{pmatrix}
\;\right)
= \frac{1}{2} \begin{pmatrix} 1+\cos ( 2\phi) & \sin ( 2\phi)\\ \sin (2\phi) & 1 - \cos ( 2\phi)\end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}
$$

which is identical to the previous result due to some basic trigonometric identities.

# 3. Combinations of Linear Transformations and Translations

## 3.1 A Plane Through the Origin

### 3.1.1 Orthogonal Projection Onto a Plane $n \cdot x = 0$ and Onto a Normal to the Plane

Consider the equation of a plane through the origin: $n_1 x_1 + n_2 x_2 + n_3 x_3 = 0$.<br>
$\quad$ Without loss of generality, assume $n_1 \ne 0$.

Viewed as a system of linear equations, we have $A x = 0$ with $A = \begin{pmatrix} n_1 & n_2 & n_3 \end{pmatrix},$ and $x = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}.$

* The rowspace $\mathscr{R}(A)$ has basis $\left\{\; n = \begin{pmatrix} n_1 \\ n_2 \\ n_3 \end{pmatrix}\;\; \right\}\quad$ (the gradient for the plane).<br>
* The null space $\mathscr{N}(A)$ has a basis $\left\{\; v_1=\begin{pmatrix} -n_2 \\ n_1 \\ 0 \end{pmatrix},\;  v_2=\begin{pmatrix} -n_3 \\ 0 \\ n_1 \end{pmatrix}\;\; \right\}$

<div style="float:left;padding-right:1cm;">
The orthogonal projection matrix into the row space is given by
$$P_\perp = \frac{1}{n\cdot n} n n^t = \frac{1}{n \cdot n} \begin{pmatrix} n^2_1 & n_1 n_2 & n_1 n_3 \\ n_2 n_1 & n^2_2 & n_2 n_3 \\ n_3 n_1 & n_3 n_2 & n^2_3\end{pmatrix}$$
</div>
<div style="float:left;padding-left:1cm;">
The orthogonal projection matrix onto the null space (i.e. the plane) is given by
$$P_\parallel = I - P_\perp = \frac{1}{n \cdot n} \begin{pmatrix} n^2_2+n^2_2 & -n_1 n_2 & -n_1 n_3 \\ -n_2 n_1 & n^2_1+n^2_3 & -n_2 n_3 \\ -n_3 n_1 & -n_3 n_2 & n^2_1+n^2_2\end{pmatrix}$$
</div>

<div style="width:70%;">

> In particular, the orthogonal projection matrices defined for the plane $x+y+z=0$ are given by<br><br>
$$
    P_\perp     =  \frac{1}{3} \begin{pmatrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{pmatrix}, \qquad\qquad
    P_\parallel =  \frac{1}{3} \begin{pmatrix} 2 & -1 & -1 \\ -1 & 2 & -1 \\ -1 & -1 & 2 \end{pmatrix}
$$
    </div>

### 3.1.2 The Mirror Image of a Point With Respect to the Plane $n \cdot x = 0$

<div style="float:left;padding-right:3cm;padding-top:0.5cm;width:40%;">
Similar to what we did above,<br>
$\quad$ an easy way to obtain the reflection of a point $A$ through the plane is to compute<br><br>

$\quad OB = OA - 2 \left( OA - OC \right),$ i.e.,<br><br>
$\quad \begin{align}\tilde{x} =&\ x - 2 P_\perp x \\ =&\ (I - 2 P_\perp) x \end{align}$

$(L)$ is the line from the origin through the orthogonal projection point $C$ in the plane.
</div>
<div style="float:left;width:30%;border:2px solid black;">
<img src="./Figs/LinTxSymLine.svg"  width="200">
</div>

The reflection matrix is given by
$$
R = I - 2 P_\perp = \frac{1}{n \cdot n} \begin{pmatrix} -n^2_1+n^2_2+n^2_3 & -2 n_1 n_2 & -2 n_1 n_3 \\ -2 n_2 n_1 & n^2_1- n^2_2+n^2_3 & -2 n_2 n_3 \\ -2 n_3 n_1 & -2 n_3 n_2 & n^2_1+n^2_2-n^2_3\end{pmatrix}
$$

<div style="width:70%;">

> In particular, the reflection matrix defined for the plane $x+y+z=0$ are given by<br><br>
$$
R = \frac{1}{3} \begin{pmatrix} 1 & -2 & -2 \\ -2 & 1 & -2 \\ -2 & -2 & 1 \end{pmatrix}
$$
</div>

#### **Implementation**

In [2]:
x1,x2,x3 = symbols("x_1,x_2,x_3", real=true); x = [x1;x2;x3]
d1,d2,d3 = symbols("d_1,d_2,d_3", real=true); d = [d1;d2;d3]
n1,n2,n3 = symbols("n_1,n_2,n_3", real=true); n = [n1;n2;n3]
b        = symbols("b",           real=true)
;

In [31]:
P_perp     = 1/dot(n,n) * n*n'
P_parallel = simplify.(diagm(ones(Sym, 3)) - P_perp)   # I - P_perp
R          = simplify.(diagm(ones(Sym, 3)) - 2*P_perp)

display(P_perp); display( P_parallel); display(R)

3×3 Array{Sym,2}:
   n_1^2/(n_1^2 + n_2^2 + n_3^2)  …  n_1*n_3/(n_1^2 + n_2^2 + n_3^2)
 n_1*n_2/(n_1^2 + n_2^2 + n_3^2)     n_2*n_3/(n_1^2 + n_2^2 + n_3^2)
 n_1*n_3/(n_1^2 + n_2^2 + n_3^2)       n_3^2/(n_1^2 + n_2^2 + n_3^2)

3×3 Array{Sym,2}:
 (n_2^2 + n_3^2)/(n_1^2 + n_2^2 + n_3^2)  …         -n_1*n_3/(n_1^2 + n_2^2 + n_3^2)
        -n_1*n_2/(n_1^2 + n_2^2 + n_3^2)            -n_2*n_3/(n_1^2 + n_2^2 + n_3^2)
        -n_1*n_3/(n_1^2 + n_2^2 + n_3^2)     (n_1^2 + n_2^2)/(n_1^2 + n_2^2 + n_3^2)

3×3 Array{Sym,2}:
 (-n_1^2 + n_2^2 + n_3^2)/(n_1^2 + n_2^2 + n_3^2)  …               -2*n_1*n_3/(n_1^2 + n_2^2 + n_3^2)
               -2*n_1*n_2/(n_1^2 + n_2^2 + n_3^2)                  -2*n_2*n_3/(n_1^2 + n_2^2 + n_3^2)
               -2*n_1*n_3/(n_1^2 + n_2^2 + n_3^2)     (n_1^2 + n_2^2 - n_3^2)/(n_1^2 + n_2^2 + n_3^2)

## 3.1 Orthogonal Projection and Reflection Through a Plane $n \cdot x = b$

A plane that does not contain the origin **does not** define a subspace of $\mathbb{R}^3.$

To use a linear transformation, we must first **translate the origin of the coordinate system** to lie in this plane, e.g.,<br><br>
$$\left.
\begin{align}
& n_1 x_1 + n_2 x_2 + n_3 x_3 = b, \quad \text{ with } \quad b \ne 0, n_1 \ne 0 \\
& \tilde{x} = T x = x + d, \text{ where } d = \begin{pmatrix} - \frac{b}{n_1} \\ 0\\0 \end{pmatrix}
\end{align}\quad \right\} \Rightarrow \quad n_1 \tilde{x}_1 + n_2 \tilde{x}_2 + n_3 \tilde{x}_3 = 0.$$

We can then use the matrices derived above to compute the projections with respect to the $\tilde{x}$ coordinate system,<br>
$\quad$ and use $T^{-1}$ to translate these back into the original coordinate system:

<div>
<div style="float:left;padding-left:1cm;padding-right:0cm;width:30%;">
Orthogonal projection into the plane:<br><br>
$\quad \boxed{x \xrightarrow{T} \tilde{x} \xrightarrow{P_\parallel} \tilde{x}_\parallel \xrightarrow{T^{-1}} x_\parallel}$
<br><br>
$\begin{align}
x_\parallel =&\  T^{-1} P_\parallel T x \\
=&\ (P_\parallel (x+d)) -d \\
=&\ P_\parallel x  + (P_\parallel -I) d \\
=&\ P_\parallel x - P_\perp d
\end{align}
$
</div>
<div style="float:left;padding-left:1cm;width:30%;border-left:2px solid black;border-right:2px solid black;">
Orthogonal Projection onto the normal to the plane:<br><br>
$\quad \boxed{x \xrightarrow{T} \tilde{x} \xrightarrow{P_\perp} \tilde{x}_\perp \xrightarrow{T^{-1}} x_\perp}$
<br><br>
$\begin{align}
x_\perp =&\  T^{-1} P_\parallel T x \\
=&\ (P_\perp (x+d)) -d \\
=&\ P_\perp x  + (P_\perp -I) d \\
=&\ P_\perp x - P_\parallel d
\end{align}
$
</div>
<div style="float:left;padding-left:1cm;width:30%;">
Reflection through the plane:<br><br>
$\quad \boxed{x \xrightarrow{T} \tilde{x} \xrightarrow{R} \tilde{x}_{mirror} \xrightarrow{T^{-1}} x_{mirror}}$
<br><br>
$\begin{align}
x_{mirror} =&\  T^{-1} R T x \\
 =&\ (R (x+d)) -d \\
 =&\ R x  - 2 P_\perp d \\
\end{align}
$<br>
$\ $where $\;\; R = I - 2 P_\perp $
</div>
</div>

#### **Implementation**

In [23]:
d = [d1;d2;d3]
x = [x1;x2;x3]

p_perp_d     = P_perp*d
p_parallel_d = P_parallel*d

3-element Array{Sym,1}:
  d_1*(n_2^2 + n_3^2)/(n_1^2 + n_2^2 + n_3^2) - d_2*n_1*n_2/(n_1^2 + n_2^2 + n_3^2) - d_3*n_1*n_3/(n_1^2 + n_2^2 + n_3^2)
 -d_1*n_1*n_2/(n_1^2 + n_2^2 + n_3^2) + d_2*(n_1^2 + n_3^2)/(n_1^2 + n_2^2 + n_3^2) - d_3*n_2*n_3/(n_1^2 + n_2^2 + n_3^2)
 -d_1*n_1*n_3/(n_1^2 + n_2^2 + n_3^2) - d_2*n_2*n_3/(n_1^2 + n_2^2 + n_3^2) + d_3*(n_1^2 + n_2^2)/(n_1^2 + n_2^2 + n_3^2)

For the plane $x + y + z = 1$, we can choose $d = \begin{pmatrix} -1 \\ 0 \\ 0 \end{pmatrix}$ to obtain

In [27]:
println("Orthogonal Projection into the plane")
x_parallel = P_parallel * x - p_perp_d
x_parallel.subs( Dict( d1=>-1, d2=>0, d3=>0, n1=>1, n2=>1, n3=> 1))

Orthogonal Projection into the plane


3×1 Array{Sym,2}:
  2*x_1/3 - x_2/3 - x_3/3 + 1/3
 -x_1/3 + 2*x_2/3 - x_3/3 + 1/3
 -x_1/3 - x_2/3 + 2*x_3/3 + 1/3

In [30]:
println("Orthogonal Projection onto the normal to the plane")
x_perp = P_perp*x - p_parallel_d
x_perp.subs( Dict( d1=>-1, d2=>0, d3=>0, n1=>1, n2=>1, n3=> 1))

Orthogonal Projection onto the normal to the plane


3×1 Array{Sym,2}:
 x_1/3 + x_2/3 + x_3/3 + 2/3
 x_1/3 + x_2/3 + x_3/3 - 1/3
 x_1/3 + x_2/3 + x_3/3 - 1/3

In [32]:
println("Reflection through the plane")
x_mirror = R*x - 2*p_perp_d
x_mirror.subs( Dict( d1=>-1, d2=>0, d3=>0, n1=>1, n2=>1, n3=> 1))

Reflection through the plane


3×1 Array{Sym,2}:
  x_1/3 - 2*x_2/3 - 2*x_3/3 + 2/3
 -2*x_1/3 + x_2/3 - 2*x_3/3 + 2/3
 -2*x_1/3 - 2*x_2/3 + x_3/3 + 2/3

#### Implementation Using Homogeneous Coordinates

In [46]:
function embed(M)
    zeros = [0;0;0]
    [ M      zeros 
     zeros'     1 ]
end
function embed(v :: Array{Sym,1})
    [v;1]
end
embed( P_perp.subs( Dict( n1=>1, n2=>1, n3=> 1)) )

4×4 Array{Sym,2}:
 1/3  1/3  1/3  0
 1/3  1/3  1/3  0
 1/3  1/3  1/3  0
   0    0    0  1

In [41]:
function T()
    [1 0 0 d1
     0 1 0 d2
     0 0 1 d3
     0 0 0 1]
end
function Tinverse()
    [1 0 0 -d1
     0 1 0 -d2
     0 0 1 -d3
     0 0 0  1]
end
;

In [48]:
PerpProj = Tinverse()*embed(P_perp) * T()

4×4 Array{Sym,2}:
   n_1^2/(n_1^2 + n_2^2 + n_3^2)  …  d_1*n_1^2/(n_1^2 + n_2^2 + n_3^2) - d_1 + d_2*n_1*n_2/(n_1^2 + n_2^2 + n_3^2) + d_3*n_1*n_3/(n_1^2 + n_2^2 + n_3^2)
 n_1*n_2/(n_1^2 + n_2^2 + n_3^2)     d_1*n_1*n_2/(n_1^2 + n_2^2 + n_3^2) + d_2*n_2^2/(n_1^2 + n_2^2 + n_3^2) - d_2 + d_3*n_2*n_3/(n_1^2 + n_2^2 + n_3^2)
 n_1*n_3/(n_1^2 + n_2^2 + n_3^2)     d_1*n_1*n_3/(n_1^2 + n_2^2 + n_3^2) + d_2*n_2*n_3/(n_1^2 + n_2^2 + n_3^2) + d_3*n_3^2/(n_1^2 + n_2^2 + n_3^2) - d_3
                               0                                                                                                                       1

In [50]:
x_perp  = PerpProj * embed(x)
x_perp.subs( Dict( d1=>-1, d2=>0, d3=>0, n1=>1, n2=>1, n3=> 1))

4×1 Array{Sym,2}:
 x_1/3 + x_2/3 + x_3/3 + 2/3
 x_1/3 + x_2/3 + x_3/3 - 1/3
 x_1/3 + x_2/3 + x_3/3 - 1/3
                           1