# 1. Display a Layout of the Gaussian Elimination Algorithm

The code int this notebook is intended as a debugging aid when writing a Gaussian Elimination Solver:<br>
starting with a matrix $A$,
* we find an elimination matrix $E1$ and update the matrix to $A1 = E1 A$. Save the computation in the augmented matrix [E1 A1]
* for each successive step, $Ei, Ai$, update the augmented matrix with [previous_augmented_matrix ; Ei Ai]
Save the pivot locations in the same way.

When the algorithm completes, we have
* the original array $A$
* the computations in another array
$$Computations =\left( \begin{array}{rr}
  E_1 & A_1 \\
  E_2 & A_2 \\
  \dots & \dots
\end{array} \right)
$$
and the pivot index pairs $p_i$ in an array or a list $( p_1, p_2, \dots p_i \dots )$.

The `ge_layout` function can now be used to display the computation.

## 1.1 Basic Display Function: build a table from the matrices

Let's start with a simple function that allows us to create titles: it outputs an
HTML `<div>` containing text of a given size and color,<br>
as well as justification of the text. See https://www.w3schools.com/Tags/tag_div.asp

In [1]:
function title( txt; sz=25,color="blue",justify="left")
    t = """<br><div style="width:30cm;color:$(color);text-align:$(justify);font-size:$(sz)px;">$(txt)</div>"""
    display(HTML(t))
end
#title("A title", justify="center", sz=40)

title (generic function with 1 method)

Next, we define a first version of the `ge_layout` function: it will accept the matrices $A$ and $Computations$,
and write these into one big table.

The routine alternates colors in the table to allow identification of the matrices,
and uses a third input (the function `to_string` to convert a table entry to an HTML string.

In [2]:
using PrettyTables, Printf
#using LaTeXStrings
# --------------------------------------------------------------------------------------------------
"""
pt_frac(value)

HTML format of Julia Fractions

# Example:
```julia-repl
julia> pt_frac(-3//5)
3 / 5
```
"""
function pt_frac(value)
    n,d=numerator(value),denominator(value)
    d == 1 ? "$n" : "$n &frasl; $d"
end
# --------------------------------------------------------------------------------------------------
"""
ge_layout( A, layers )

Display a computational layout for a Gaussian Elimination Computation

# Arguments
- `n::Array`:         an array of integers or rational numbers
- `layers::Array`:    an array of the computations
- `to_str::Function`: a function converting a matrix entry to a string

# Example:
```julia-repl
julia> ge_layout( A, [ E1 A1; E2 A2; E3 A3], to_str = pt_real") # E_{i} is the i'th elemination matrix, A_i = E_i * A_{i-1}
the layout
```
"""
function ge_layout( A, layers, to_str = pt_frac )
    n  = size(A, 1)
    tf = HTMLTableFormat(css=""".verticalline { border-right: 1px solid black; height: 100%; }""" )

    # define a vertical divider (here we use '|'), and rearrange the table entries to put it in place
    #sp = fill("&nbsp;", n+size(layers,1),1 )
    sp = fill("<span class=verticalline></span>", n+size(layers,1), 1)
    MA = vcat( hcat( fill("", n,n), map(to_str, A)),
                     map( to_str,  layers))
    M   = [MA[:,1:n] sp MA[:,n+1:end]]

    # Now add the background colors for the matrices
    bg_gray_1    = HTMLHighlighter((data,i,j)->iseven((i-1)÷n+1)        && j>n,  HTMLDecoration(background = "#F0F0F0", color = "blue"  ))
    bg_gray_2    = HTMLHighlighter((data,i,j)->isodd( (i-1)÷n+1)        && j>n,  HTMLDecoration(background = "#FBFAFA", color = "blue"  ))

    bg_yellow_1  = HTMLHighlighter((data,i,j)->iseven((i-1)÷n+1)        && j<=n, HTMLDecoration(background = "#FDFAD4", color = "blue"  ))
    bg_yellow_2  = HTMLHighlighter((data,i,j)->i>n && isodd( (i-1)÷n+1) && j<=n, HTMLDecoration(background = "#F6EFA1", color = "blue"  ))
    bg_white     = HTMLHighlighter((data,i,j)->i<=n                     && j<=n, HTMLDecoration(background = "#FFFFFF", color = "blue"  ))

    # create and return the table
    pretty_table( M, noheader = true, highlighters=(bg_white,bg_gray_1,bg_gray_2,bg_yellow_1,bg_yellow_2), tf=tf, backend = :html )
end

ge_layout

## 1.2 Gaussian Elimination for a given matrix $A$

Here, we do the computation 'by hand'

In [3]:
# Look at the following matrix
A  = [ 1 3 1 4;
      -2 5 5 6;
       1 3 1 5;
       2 2 8 2
     ]
# The GE algorithm results in the following steps
p1 = (1,1)
E1 = [ 1 0 0 0;
       2 1 0 0;
      -1 0 1 0;
      -2 0 0 1
    ]
A1 = E1 * A

p2 = (2,2)
E2 = [ 1 0 0 0;
       0 1 0 0;
       0 0 1 0;
       0 4//11 0 1
    ]
A2 = E2 * A1

p3 = (4,3)
E3 = [ 1 0 0 0;
       0 1 0 0;
       0 0 0 1;
       0 0 1 0
    ]
A3 = E3 * A2

# Let's display the computation
title("Gaussian Elimination Example")
ge_layout( A, [E1 A1; E2 A2; E3 A3])

HTML{String}("<br><div style=\"width:30cm;color:blue;text-align:left;font-size:25px;\">Gaussian Elimination Example</div>")

<!DOCTYPE html>
 
 

 
 
 
 
 
 
 
 
 1 
 3 
 1 
 4 
 
 
 
 
 
 
 
 -2 
 5 
 5 
 6 
 
 
 
 
 
 
 
 1 
 3 
 1 
 5 
 
 
 
 
 
 
 
 2 
 2 
 8 
 2 
 
 
 1 
 0 
 0 
 0 
 
 1 
 3 
 1 
 4 
 
 
 2 
 1 
 0 
 0 
 
 0 
 11 
 7 
 14 
 
 
 -1 
 0 
 1 
 0 
 
 0 
 0 
 0 
 1 
 
 
 -2 
 0 
 0 
 1 
 
 0 
 -4 
 6 
 -6 
 
 
 1 
 0 
 0 
 0 
 
 1 
 3 
 1 
 4 
 
 
 0 
 1 
 0 
 0 
 
 0 
 11 
 7 
 14 
 
 
 0 
 0 
 1 
 0 
 
 0 
 0 
 0 
 1 
 
 
 0 
 4 ⁄ 11 
 0 
 1 
 
 0 
 0 
 94 ⁄ 11 
 -10 ⁄ 11 
 
 
 1 
 0 
 0 
 0 
 
 1 
 3 
 1 
 4 
 
 
 0 
 1 
 0 
 0 
 
 0 
 11 
 7 
 14 
 
 
 0 
 0 
 0 
 1 
 
 0 
 0 
 94 ⁄ 11 
 -10 ⁄ 11 
 
 
 0 
 0 
 1 
 0 
 
 0 
 0 
 0 
 1

Note that we used exact arithmetic, and displayed the resulting fractions.<br>
We could convert the fractions to floating point numbers by passing a function
into the `ge_layout` routine: `value->@sprintf( "%8.2f", value)`
converts an entry value to a string of width 8 characters, with 2 decimal places.

Note the width should be at least number of decimal places + 6

In [4]:
title("Gaussian Elimination Example<br>with rounding")
ge_layout(A, [E1 A1; E2 A2; E3 A3], value->@sprintf( "%8.2f", value) )

HTML{String}("<br><div style=\"width:30cm;color:blue;text-align:left;font-size:25px;\">Gaussian Elimination Example<br>with rounding</div>")

<!DOCTYPE html>
 
 

 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 
 
 
 
 
 -2.00 
 5.00 
 5.00 
 6.00 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 5.00 
 
 
 
 
 
 
 
 2.00 
 2.00 
 8.00 
 2.00 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 2.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 -1.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 
 -2.00 
 0.00 
 0.00 
 1.00 
 
 0.00 
 -4.00 
 6.00 
 -6.00 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 0.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 0.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 
 0.00 
 0.36 
 0.00 
 1.00 
 
 0.00 
 0.00 
 8.55 
 -0.91 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 0.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 0.00 
 0.00 
 8.55 
 -0.91 
 
 
 0.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00

## 1.3 Modify ge_layout to highlight the pivots

Let's create a somewhat more sophisticated version of `ge_layout`: add a font color for the pivots

In [5]:
function ge_layout( A, layers, pivots; to_str = pt_frac, extra_cols=0 )
    n,m  = size(A)
    m   -= extra_cols
    # table entry indices for the pivots; note j+m+1 to account for the inserted separator |
    # this tuple of index pairs will have corresponding entries colored magenta
    p    = ( ((l-1)*n+i, (j+n+1))  for (l,(i,j)) in enumerate(pivots))

    hl = (
        # Pivot positions; alternate matrix backgrounds with iseven, isodd
        HTMLHighlighter((data,i,j)->iseven((i-1)÷n+1)        && j>n && (i,j) in p,
            HTMLDecoration(background = "#F0F0F0", color = "magenta" )),
        HTMLHighlighter((data,i,j)->isodd( (i-1)÷n+1)        && j>n && (i,j) in p,
            HTMLDecoration(background = "#FBFAFA", color = "magenta" )),

        HTMLHighlighter((data,i,j)->iseven((i-1)÷n+1)        && j<=n && (i,j) in p,
            HTMLDecoration(background = "#FDFAD4", color = "magenta" )),
        HTMLHighlighter((data,i,j)->i>n && isodd( (i-1)÷n+1) && j<=n && (i,j) in p,
            HTMLDecoration(background = "#F6EFA1", color = "magenta" )),
        HTMLHighlighter((data,i,j)->i<=n                     && j<=n && (i,j) in p,
            HTMLDecoration(background = "#FFFFFF", color = "magenta" )),

        # non pivot positions
        HTMLHighlighter((data,i,j)->iseven((i-1)÷n+1)        && j>n,
            HTMLDecoration(background = "#F0F0F0", color = "blue" )),
        HTMLHighlighter((data,i,j)->isodd( (i-1)÷n+1)        && j>n,
            HTMLDecoration(background = "#FBFAFA", color = "blue" )),

        HTMLHighlighter((data,i,j)->iseven((i-1)÷n+1)        && j<=n,
            HTMLDecoration(background = "#FDFAD4", color = "blue" )),
        HTMLHighlighter((data,i,j)->i>n && isodd( (i-1)÷n+1) && j<=n,
            HTMLDecoration(background = "#F6EFA1", color = "blue" )),
        HTMLHighlighter((data,i,j)->i<=n                     && j<=n,
            HTMLDecoration(background = "#FFFFFF", color = "blue" ))
    )

    tf  = HTMLTableFormat(css=""".verticalline { border-right: 1px solid black; height: 100%; }""" ) # dividing line css
    if length( layers ) > 0
        MA  = vcat( hcat( fill("", n,n), map(to_str, A)), # *  A
                    map( to_str, layers))                 # Ei Ai

        sp  = fill("<span class=verticalline></span>", n+size(layers,1), 1)  # dividing line
        if extra_cols > 0 # need a divider in cols n+1 and m+n+2
            M   = [MA[:,1:n] sp MA[:,n+1:n+m] sp MA[:, n+1+m:end]]
        else
            M   = [MA[:,1:n] sp MA[:,n+1:end]]
        end
    else
        M = hcat( fill("", n,n), fill("<span class=verticalline></span>", n,1), map(to_str, A))
    end

    pretty_table( M, noheader = true, highlighters=hl, tf=tf, backend = :html )
end
ge_layout( A, [E1 A1; E2 A2; E3 A3], (p1,p2,p3), to_str=value->@sprintf( "% 8.2f", value) )

<!DOCTYPE html>
 
 

 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 
 
 
 
 
 -2.00 
 5.00 
 5.00 
 6.00 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 5.00 
 
 
 
 
 
 
 
 2.00 
 2.00 
 8.00 
 2.00 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 2.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 -1.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 
 -2.00 
 0.00 
 0.00 
 1.00 
 
 0.00 
 -4.00 
 6.00 
 -6.00 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 0.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 0.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 
 0.00 
 0.36 
 0.00 
 1.00 
 
 0.00 
 0.00 
 8.55 
 -0.91 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 0.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 0.00 
 0.00 
 8.55 
 -0.91 
 
 
 0.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00

## 1.4 Add a slider to animate the computation

As an experiment, let's add a slider to show the computations one set of $E_i A_i$ matrices at a time.

Note: not really worth it; the display flickers (Also WebIO has a bug which requires reloading the page to actually work)

In [6]:
# Remark: for me, this works in Chromium but not in Firefox
using Interact

ge_steps  = [E1 A1; E2 A2; E3 A3]
N_steps   = Int64(size(ge_steps,1)/size(A,1))
step_ctrl = slider(0:N_steps,value=0,label="Step")
display.([step_ctrl] )

function show_step(i)
#h = on(step_ctrl) do i
    IJulia.clear_output(true)
    display.([step_ctrl])
    title( "Gaussian Elimination Step $i")
    ge_layout( A, ge_steps[1:i*size(A,1),:],(p1,p2,p3), to_str=value->@sprintf( "% 8.2f", value) )
end

#Interact.@on show_step( &step_ctrl )
on( show_step, step_ctrl)

step_ctrl[] = 0;

(div { className="field interact-widget" }
    (div { className="interact-flex-row interact-widget" }
    (div { className="interact-flex-row-left" }
      (label { className="interact " style=Dict{Any,Any}(:padding => "5px 10px 0px 10px") }
        "Step"))
    (div { className="interact-flex-row-center" }
      (input { max=3 min=0 attributes=Dict{Any,Any}(:type => "range",Symbol("data-bind") => "numericValue: index, valueUpdate: 'input', event: {change: function (){this.changes(this.changes()+1)}}","orient" => "horizontal") step=1 className="slider slider is-fullwidth" style=Dict{Any,Any}() }))
    (div { className="interact-flex-row-right" }
      (p { attributes=Dict("data-bind" => "text: formatted_val") }))))

HTML{String}("<br><div style=\"width:30cm;color:blue;text-align:left;font-size:25px;\">Gaussian Elimination Step 0</div>")

<!DOCTYPE html>
 
 

 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 
 
 
 
 
 -2.00 
 5.00 
 5.00 
 6.00 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 5.00 
 
 
 
 
 
 
 
 2.00 
 2.00 
 8.00 
 2.00

Alternatively, we could use the sleep function to put in a delay...

In [7]:
# Alternatively, we could use a timer....
ge_steps  = [E1 A1; E2 A2; E3 A3]
N_steps   = Int64(size(ge_steps,1)/size(A,1))

title( "GE step 0")
ge_layout(A, [], (p1,p2,p3) )
for i = 1:N_steps
    sleep(4)
    IJulia.clear_output(true)
    title( "GE step $i")
    ge_layout(A, ge_steps[1:i*size(A,1),:], (p1,p2,p3), to_str=value->@sprintf( "% 8.2f", value) )
end

HTML{String}("<br><div style=\"width:30cm;color:blue;text-align:left;font-size:25px;\">GE step 3</div>")

<!DOCTYPE html>
 
 

 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 
 
 
 
 
 -2.00 
 5.00 
 5.00 
 6.00 
 
 
 
 
 
 
 
 1.00 
 3.00 
 1.00 
 5.00 
 
 
 
 
 
 
 
 2.00 
 2.00 
 8.00 
 2.00 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 2.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 -1.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 
 -2.00 
 0.00 
 0.00 
 1.00 
 
 0.00 
 -4.00 
 6.00 
 -6.00 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 0.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 0.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 
 0.00 
 0.36 
 0.00 
 1.00 
 
 0.00 
 0.00 
 8.55 
 -0.91 
 
 
 1.00 
 0.00 
 0.00 
 0.00 
 
 1.00 
 3.00 
 1.00 
 4.00 
 
 
 0.00 
 1.00 
 0.00 
 0.00 
 
 0.00 
 11.00 
 7.00 
 14.00 
 
 
 0.00 
 0.00 
 0.00 
 1.00 
 
 0.00 
 0.00 
 8.55 
 -0.91 
 
 
 0.00 
 0.00 
 1.00 
 0.00 
 
 0.00 
 0.00 
 0.00 
 1.00

# 2. Coding Assignment

Create a function that takes a matrix as an input, and returns a corresponding row echelon form.<br>
You might consider using `ge_layout` for debugging your code.

In [8]:
function row_echelon_form(A)
    M,N = size(A)
    println("The matrix A has size $M x $N")
    display(A)
    
    # make a copy of A: we will modify the copy, not A itself
    R = copy(A)
    # < your code here > ***************************************************** <<<<<< 
    R
end

row_echelon_form (generic function with 1 method)

In [9]:
row_echelon_form(A);

4×4 Array{Int64,2}:
  1  3  1  4
 -2  5  5  6
  1  3  1  5
  2  2  8  2

The matrix A has size 4 x 4


## 2.1 Some code building blocks

### 2.1.1 Submatrices

In [10]:
println("A vector:  row_index=1")
A[1, 1:3]

A vector:  row_index=1


3-element Array{Int64,1}:
 1
 3
 1

In [11]:
println( "A matrix (row vector): row_index=1:1")
A[1:1, 1:3]

A matrix (row vector): row_index=1:1


1×3 Array{Int64,2}:
 1  3  1

In [12]:
println( "A column vector: transpose of a row vector")
A[1:1,1:3]'

A column vector: transpose of a row vector


3×1 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1
 3
 1

### 2.1.2 Conditional Statements

In [13]:
if 3 > 1 && 8 < 9
    println( "if branch")
else
    println( "else branch")
end

if branch


### 2.1.3 Loop statements `for loops`

In [14]:
for i in 1:10
    print( " $i")
end

 1 2 3 4 5 6 7 8 9 10

In [15]:
# premature temination of the loop
for i in 1:10
    print( " $i")
    if i > 4
        break
    end
end

 1 2 3 4 5

In [16]:
# skip some code inside a loop
for i in 1:10
    if i > 3 && i < 8
        continue
    end
    print( " $i")
end

 1 2 3 8 9 10

# 2.2 Needed functionality: code snippets you will need to write

> * given  a current row and column, find a pivot
> * interchange rows in a matrix
> * use a pivot row to produce a zero at some location in a row (the elimination operation)
> * possibly scale a row

In [17]:
display(A)
# R_2 <- R_2 + 2 R_1
A[2:2, : ]  = A[2:2, :] + 2 * A[1:1, :]
A

4×4 Array{Int64,2}:
  1  3  1  4
 -2  5  5  6
  1  3  1  5
  2  2  8  2

4×4 Array{Int64,2}:
 1   3  1   4
 0  11  7  14
 1   3  1   5
 2   2  8   2

In [18]:
# R_3 <-> R_4
A[3:3,:], A[4:4,:] = A[4:4,:], A[3:3,:]
A

4×4 Array{Int64,2}:
 1   3  1   4
 0  11  7  14
 2   2  8   2
 1   3  1   5

In [19]:
# If we want to construct an elementary operation matrix:
if false  # temporarily set to true if you have not yet downloaded the LinearAlgebra library
    using Pkg
    Pkg.add("LinearAlgebra")
end

using LinearAlgebra

In [20]:
display( I )     # an identity matrix of arbitrary size
display( 1.0I )  # a floating point identity matrix of arbitrary size
display("-----------------------------------")
E = Matrix(1.0I, 4, 4) # A 4x4 floating point identity matrix
display(E)

UniformScaling{Bool}
true*I

UniformScaling{Float64}
1.0*I

"-----------------------------------"

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [21]:
E[2:end,1]=[1 3 4]
E

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 3.0  0.0  1.0  0.0
 4.0  0.0  0.0  1.0

In [22]:
title("Have fun!")

HTML{String}("<br><div style=\"width:30cm;color:blue;text-align:left;font-size:25px;\">Have fun!</div>")

# 3. Having fun: what if we have errors in A?

In [23]:
using Measurements, LinearAlgebra

## 3.1 Errors in the matrix

In [24]:
A = randn((3,3)) .± 0.001randn((3,3))
display( A )
b=[1.; 1.; 0.]
x = A \ b
display(x)
norm(A*x-b)

3×3 Array{Measurement{Float64},2}:
 -2.92177±-0.00039   0.62798±-0.00056  0.58779±-6.2e-5 
  0.04514±0.0006    -1.84353±0.00067    0.1632±-0.0011 
  1.10356±-0.00013    0.0823±0.00021   1.34385±-0.00016

3-element Array{Measurement{Float64},1}:
 -0.38434 ± 0.00011
 -0.52108 ± 0.0003 
  0.34753 ± 0.00013

1.1102e-16 ± 1.3e-19

In [25]:
# However, if the system is inconsistent, we have
A = [randn((2,3)); 0 0 0]
A = A .± 0.001randn((3,3))

3×3 Array{Measurement{Float64},2}:
 -0.59785±-0.0002  -0.4282±-0.00085  1.66687±1.4e-5 
   0.4047±0.001    -0.8243±0.0011    0.56976±0.00052
      0.0±0.00084      0.0±-0.00035      0.0±0.00099

In [26]:
A \ b

3-element Array{Measurement{Float64},1}:
 NaN ± NaN
 NaN ± NaN
 NaN ± NaN

## 3.2 Errors in the right hand side

In [27]:
A = randn((3,3))
display( A )
b=[1.; 1.; 0.] .± 0.01randn((3,1))
x = A \ b
display(x)
norm(A*x-b)

3×3 Array{Float64,2}:
 -1.37373   0.596578  -0.371613 
  0.353479  1.72905   -1.03149  
  1.26162   1.389     -0.0978416

3×1 Array{Measurement{Float64},2}:
 -0.432 ± 0.016
  0.356 ± 0.017
 -0.521 ± 0.025

1.13e-16 ± 2.8e-18

## 3.3 Errors in both the matrix and the right hand side

In [28]:
A = randn((3,3)) .± 0.1randn((3,3))
display( A )
b=[1.; 1.; 0.] .± 0.1randn((3,1))
x = A \ b
display(x)
norm(A*x-b)

3×3 Array{Measurement{Float64},2}:
 1.208±-0.046   1.878±0.0034   0.22±-0.22 
 0.086±0.059   -0.505±0.021   -0.84±-0.2  
  -2.6±-0.11   -1.794±0.057   0.564±-0.072

3×1 Array{Measurement{Float64},2}:
 -2.12 ± 0.99
   2.2 ± 1.0 
  -2.7 ± 1.2 

8.7e-16 ± 1.6e-16

## 3.4 What if the system is almost inconsistent

In [29]:
A = [randn((2,3)); 0 0 1e-10]
b = [1;1;1]
x = A \ b
display(A); display(b); display(x)
norm(A*x-b)

3×3 Array{Float64,2}:
 1.70025    0.898233  0.260984
 0.448169  -0.975361  0.155746
 0.0        0.0       1.0e-10 

3-element Array{Int64,1}:
 1
 1
 1

3-element Array{Float64,1}:
 -1.9139526052860756e9
  7.173547708987852e8 
  1.0e10              

4.76837158203125e-7