<div style="height:2cm;">
<div style="float:center;width:100%;text-align:center;"><strong style="height:100px;color:darkred;font-size:40px;">Low Level Display Routines (deprecated)</strong>
</div></div>

GE layout rendering is covered in [A2_Matrix_Layout_Displays.ipynb](A2_Matrix_Layout_Displays.ipynb).
Use `la_figures.ge(...)` there for visualization when needed.


High Level Routines are shown in [**A2_Matrix_Layout_displays.ipynb**](A2_Matrix_Layout_displays.ipynb)

# 1. Display a Layout of the Gaussian Elimination Algorithm

The code int this notebook is intended as a debugging aid when writing a Gaussian Elimination Solver:<br>
starting with a matrix $A$,
* we find an elimination matrix $E_1$ and update the matrix to $A1 = E_1 A$. Save the computation in the augmented matrix [E_1 A_1]
* for each successive step, $E_i, A_i$, update the augmented matrix with [previous_augmented_matrix ; E_i A_i]
Save the pivot locations in the same way.

When the algorithm completes, we have
* the original array $A$
* the computations in another array<br>
$\qquad Computations =\left( \begin{array}{rr}
  E_1 & A_1 \\
  E_2 & A_2 \\
  \dots & \dots
\end{array} \right)
$

and the pivot index pairs $p_i$ in an array or a list $( p_1, p_2, \dots p_i \dots )$.

The `ge_layout` function can now be used to display the computation.

## 1.1 Basic Display Function: build a table from the matrices (DEPRECATED)

**Remark**>br>
With the advent of the CTAN nicematrix package, the following functions are deprecated.<br>
The replacement package `itikz` generates a matrix of matrices with proper alignment and decorations.

____
Let's start with a simple function that allows us to create titles: it outputs an
HTML `<div>` containing text of a given size and color,<br>
as well as justification of the text. See https://www.w3schools.com/Tags/tag_div.asp

**Remark:** This function is now part of GenLinAlgProblems as function `pr()`

Next, we define a first version of the `ge_layout` function: it will accept the matrices $A$ and $Computations$,
and write these into one big table.

The routine alternates colors in the table to allow identification of the matrices,
and uses a third input (the function `to_string` to convert a table entry to an HTML string.

## 1.2 Gaussian Elimination for a given matrix $A$

Here, we do the computation 'by hand'

Note that we used exact arithmetic, and displayed the resulting fractions.<br>
We could convert the fractions to floating point numbers by passing a function
into the `ge_layout` routine: `value->@sprintf( "%8.2f", value)`
converts an entry value to a string of width 8 characters, with 2 decimal places.

Note the width should be at least number of decimal places + 6

## 1.3 Modify ge_layout to highlight the pivots

Let's create a somewhat more sophisticated version of `ge_layout`: add a font color for the pivots

## 1.4 Add a slider to animate the computation

As an experiment, let's add a slider to show the computations one set of $E_i A_i$ matrices at a time.

Note: not really worth it; the display flickers (Also WebIO has a bug which requires reloading the page to actually work)

Alternatively, we could use the sleep function to put in a delay...

# 2. Coding Assignment

Create a function that takes a matrix as an input, and returns a corresponding row echelon form.<br>
You might consider using `ge_layout` for debugging your code.

In [8]:
function row_echelon_form(A)
    M,N = size(A)
    println("The matrix A has size $M x $N")
    display(A)

    # make a copy of A: we will modify the copy, not A itself
    R = copy(A)
    # < your code here > ***************************************************** <<<<<< 
    R
end

row_echelon_form (generic function with 1 method)

In [9]:
row_echelon_form(A);

The matrix A has size 4 x 4


4×4 Matrix{Int64}:
  1  3  1  4
 -2  5  5  6
  1  3  1  5
  2  2  8  2

## 2.1 Some code building blocks

### 2.1.1 Submatrices

In [10]:
println("A vector:  row_index=1")
A[1, 1:3]

A vector:  row_index=1


3-element Vector{Int64}:
 1
 3
 1

In [11]:
println( "A matrix (row vector): row_index=1:1")
A[1:1, 1:3]

A matrix (row vector): row_index=1:1


1×3 Matrix{Int64}:
 1  3  1

In [12]:
println( "A column vector: transpose of a row vector")
A[1:1,1:3]'

A column vector: transpose of a row vector


3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 3
 1

### 2.1.2 Conditional Statements

In [13]:
if 3 > 1 && 8 < 9
    println( "if branch")
else
    println( "else branch")
end

if branch


### 2.1.3 Loop statements `for loops`

In [14]:
for i in 1:10
    print( " $i")
end

 1 2 3 4 5 6 7 8 9 10

In [15]:
# premature temination of the loop
for i in 1:10
    print( " $i")
    if i > 4
        break
    end
end

 1 2 3 4 5

In [16]:
# skip some code inside a loop
for i in 1:10
    if i > 3 && i < 8
        continue
    end
    print( " $i")
end

 1 2 3 8 9 10

# 2.2 Needed functionality: code snippets you will need to write

> * given  a current row and column, find a pivot
> * interchange rows in a matrix
> * use a pivot row to produce a zero at some location in a row (the elimination operation)
> * possibly scale a row

In [17]:
display(A)
# R_2 <- R_2 + 2 R_1
A[2:2, : ]  = A[2:2, :] + 2 * A[1:1, :]
A

4×4 Matrix{Int64}:
  1  3  1  4
 -2  5  5  6
  1  3  1  5
  2  2  8  2

4×4 Matrix{Int64}:
 1   3  1   4
 0  11  7  14
 1   3  1   5
 2   2  8   2

In [18]:
# R_3 <-> R_4
A[3:3,:], A[4:4,:] = A[4:4,:], A[3:3,:]
A

4×4 Matrix{Int64}:
 1   3  1   4
 0  11  7  14
 2   2  8   2
 1   3  1   5

In [19]:
# If we want to construct an elementary operation matrix:
if false  # temporarily set to true if you have not yet downloaded the LinearAlgebra library
    using Pkg
    Pkg.add("LinearAlgebra")
end

using LinearAlgebra

In [20]:
display( I )     # an identity matrix of arbitrary size
display( 1.0I )  # a floating point identity matrix of arbitrary size
display("-----------------------------------")
E = Matrix(1.0I, 4, 4) # A 4x4 floating point identity matrix
display(E)

UniformScaling{Bool}
true*I

UniformScaling{Float64}
1.0*I

"-----------------------------------"

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [21]:
E[2:end,1]=[1 3 4]
E

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 3.0  0.0  1.0  0.0
 4.0  0.0  0.0  1.0

In [22]:
title("Have fun!")

HTML{String}("<br><div style=\"width:30cm;color:blue;text-align:left;font-size:25px;\">Have fun!</div>")

# 3. Having fun: what if we have errors in A?

In [23]:
using Measurements, LinearAlgebra

LoadError: ArgumentError: Package Measurements not found in current path.
- Run `import Pkg; Pkg.add("Measurements")` to install the Measurements package.

## 3.1 Errors in the matrix

In [24]:
A = randn((3,3)) .± 0.001randn((3,3))
display( A )
b=[1.; 1.; 0.]
x = A \ b
display(x)
norm(A*x-b)

LoadError: UndefVarError: `±` not defined

In [25]:
# However, if the system is inconsistent, we have
A = [randn((2,3)); 0 0 0]
A = A .± 0.001randn((3,3))

LoadError: UndefVarError: `±` not defined

In [26]:
A \ b

LoadError: UndefVarError: `b` not defined

## 3.2 Errors in the right hand side

In [27]:
A = randn((3,3))
display( A )
b=[1.; 1.; 0.] .± 0.01randn((3,1))
x = A \ b
display(x)
norm(A*x-b)

3×3 Matrix{Float64}:
 -0.720009   1.33033    0.911436
  1.92877   -0.432259  -2.29562
 -0.304979  -0.583963   1.08448

LoadError: UndefVarError: `±` not defined

## 3.3 Errors in both the matrix and the right hand side

In [28]:
A = randn((3,3)) .± 0.1randn((3,3))
display( A )
b=[1.; 1.; 0.] .± 0.1randn((3,1))
x = A \ b
display(x)
norm(A*x-b)

LoadError: UndefVarError: `±` not defined

## 3.4 What if the system is almost inconsistent

In [29]:
A = [randn((2,3)); 0 0 1e-10]
b = [1;1;1]
x = A \ b
display(A); display(b); display(x)
norm(A*x-b)

3×3 Matrix{Float64}:
 -1.44016    -0.233279  -0.0595905
  0.0539813   0.628903   0.777773
  0.0         0.0        1.0e-10

3-element Vector{Int64}:
 1
 1
 1

3-element Vector{Float64}:
  1.61187846687668e9
 -1.2505495186913845e10
  1.0e10

1.9110702922202824e-6